/*    This SQL DDL script was generated by Microsoft Visual Studio (Release Date: LOCAL BUILD). */

/*    Driver Used : Microsoft Visual Studio - Microsoft SQL Server Driver.                    */
/*    Document    : C:\Users\Shahrukh\Desktop\Desktop\Semester 6\Software Engineering 2\Projects\SE2 Project ERD - Copy.vsd. */
/*    Time Created: April 4, 2014 10:19 PM.                                                   */
/*    Operation   : From Visio Generate Wizard.                                               */
/*    Connected data source : No connection.                                                  */
/*    Connected server      : No connection.                                                  */
/*    Connected database    : Not applicable.                                                 */



SET QUOTED_IDENTIFIER ON

go


/* Create APIv2 database.                                                                     */
use master  

go

create database "APIv2"  

go

use "APIv2"  

go

/* Create new table "Debt".                                                                   */
/* "Debt" : Table of Debt                                                                     */
/* 	"DebtId" : DebtId identifies Debt                                                         */
/* 	"DealDate" : DealDate is of Debt                                                          */
/* 	"Total" : Total is of Debt                                                                */
/* 	"Balance" : Balance is of Debt                                                            */
/* 	"LastPaymentDate" : LastPaymentDate is of Debt                                            */
/* 	"PartyId" : PartyId partly identifies Debt                                                */  
create table "Debt" ( 
	"DebtId" int not null identity(1,1),
	"DealDate" smalldatetime null,
	"Total" money null,
	"Payed" money null,
	"LastPaymentDate" smalldatetime null,
	"PartyId" int not null)  

go

alter table "Debt"
	add constraint "Debt_PK" primary key ("DebtId")   


go

                                             
create table "DebtDetails" ( 
	"Id" int not null identity(1,1),
	"Qty" int null,
	"SellPrice" money null,
	"PartNo" varchar(100) not null,
	"DebtId" int not null)  

go

alter table "DebtDetails"
	add constraint "DebtDetails_PK" primary key ("Id")   


go

/* Create new table "Expenses".                                                               */
/* "Expenses" : Table of Expenses                                                             */
/* 	"Id" : Id identifies Expenses                                                             */
/* 	"Name" : Name is of Expenses                                                              */
/* 	"Amount" : Amount is of Expenses                                                          */
/* 	"Date" : Date is of Expenses                                                              */  
create table "Expenses" ( 
	"Id" int not null identity(1,1),
	"Name" varchar(100) null,
	"Amount" money null,
	"Date" smalldatetime null)  

go

alter table "Expenses"
	add constraint "Expenses_PK" primary key ("Id")   


go

/* Create new table "Party".                                                                  */
/* "Party" : Table of Party                                                                   */
/* 	"Name" : Name identifies Party                                                            */
/* 	"Location" : Location is of Party                                                         */
/* 	"Id" : Id identifies Party                                                                */  
create table "Party" ( 
	"Name" varchar(100) null,
	"Location" varchar(100) null,
	"Id" int not null identity(1,1))  

go

alter table "Party"
	add constraint "Party_PK" primary key ("Id")   


go

/* Create new table "Sales".                                                                  */
/* "Sales" : Table of Sales                                                                   */
/* 	"PartNo" : PartNo partly identifies Sales                                                 */
/* 	"SellingPrice" : SellingPrice is of Sales                                                 */
/* 	"DateSold" : DateSold is of Sales                                                         */
/* 	"CustomerType" : CustomerType is of Sales                                                 */
/* 	"PartyId" : PartyId partly identifies Sales                                               */
/* 	"Qty" : Qty is of Sales                                                                   */
/* 	"Id" : Id identifies Sales                                                                */  
create table "Sales" ( 
	"PartNo" varchar(100) not null,
	"SellingPrice" money null,
	"DateSold" smalldatetime null,
	"CustomerType" varchar(50) null,
	"PartyId" int not null,
	"Qty" int null,
	"Id" int not null identity(1,1))  

go

alter table "Sales"
	add constraint "Sales_PK" primary key ("Id")   


go

/* Create new table "Inventory".                                                              */
/* "Inventory" : Table of Inventory                                                           */
/* 	"PartNo" : PartNo identifies Inventory                                                    */
/* 	"Qty" : Qty is of Inventory                                                               */
/* 	"StoreId" : StoreId partly identifies Inventory                                           */  
create table "Inventory" ( 
	"PartNo" varchar(100) not null,
	"Qty" int null,
	"StoreId" int not null)  

go

alter table "Inventory"
	add constraint "Inventory_PK" primary key ("PartNo", "StoreId")   


go

/* Create new table "Store".                                                                  */
/* "Store" : Table of Store                                                                   */
/* 	"Id" : Id identifies Store                                                                */
/* 	"Name" : Name is of Store                                                                 */
/* 	"Type" : Type is of Store                                                                 */  
create table "Store" ( 
	"Id" int not null identity(1,1),
	"Name" varchar(50) null,
	"Type" varchar(50) null)  

go

alter table "Store"
	add constraint "Store_PK" primary key ("Id")   


go

/* Create new table "Parts".                                                                  */
/* "Parts" : Table of Parts                                                                   */
/* 	"PartNo" : PartNo identifies Parts                                                        */
/* 	"Name" : Name is of Parts                                                                 */
/* 	"Model" : Model is of Parts                                                               */
/* 	"Car " : Car  is of Parts                                                                 */
/* 	"CostPrice" : CostPrice is of Parts                                                       */  
create table "Parts" ( 
	"PartNo" varchar(100) not null,
	"Name" varchar(50) null,
	"Model" varchar(50) null,
	"Car " varchar(50) null,
	"CostPrice" money null)  

go

alter table "Parts"
	add constraint "Parts_PK" primary key ("PartNo")   


go

/* Create new table "Purchase".                                                               */
/* "Purchase" : Table of Purchase                                                             */
/* 	"SellingPrice" : SellingPrice identifies Purchase                                         */
/* 	"DatePurchased" : DatePurchased is of Purchase                                            */
/* 	"PartyId" : PartyId partly identifies Purchase                                            */
/* 	"Qty" : Qty is of Purchase                                                                */
/* 	"PartNo" : PartNo partly identifies Purchase                                              */
/* 	"Id" : Id identifies Purchase                                                             */  
create table "Purchase" ( 
	"SellingPrice" money null,
	"DatePurchased" smalldatetime null,
	"PartyId" int not null,
	"Qty" int null,
	"PartNo" varchar(100) not null,
	"Id" int not null identity(1,1))  

go

alter table "Purchase"
	add constraint "Purchase_PK" primary key ("Id")   


go

/* Add foreign key constraints to table "Debt".                                               */
alter table "Debt"
	add constraint "Party_Debt_FK1" foreign key (
		"PartyId")
	 references "Party" (
		"Id") on update no action on delete no action  

go

/* Add foreign key constraints to table "DebtDetails".                                        */
alter table "DebtDetails"
	add constraint "Parts_DebtDetails_FK1" foreign key (
		"PartNo")
	 references "Parts" (
		"PartNo") on update no action on delete no action  

go

alter table "DebtDetails"
	add constraint "Debt_DebtDetails_FK1" foreign key (
		"DebtId")
	 references "Debt" (
		"DebtId") on update no action on delete no action  

go

/* Add foreign key constraints to table "Sales".                                              */
alter table "Sales"
	add constraint "Parts_Sales_FK1" foreign key (
		"PartNo")
	 references "Parts" (
		"PartNo") on update no action on delete no action  

go

alter table "Sales"
	add constraint "Party_Sales_FK1" foreign key (
		"PartyId")
	 references "Party" (
		"Id") on update no action on delete no action  

go

/* Add foreign key constraints to table "Inventory".                                          */
alter table "Inventory"
	add constraint "Parts_Inventory_FK1" foreign key (
		"PartNo")
	 references "Parts" (
		"PartNo") on update no action on delete no action  

go

alter table "Inventory"
	add constraint "Store_Inventory_FK1" foreign key (
		"StoreId")
	 references "Store" (
		"Id") on update no action on delete no action  

go

/* Add foreign key constraints to table "Purchase".                                           */
alter table "Purchase"
	add constraint "Parts_Purchase_FK1" foreign key (
		"PartNo")
	 references "Parts" (
		"PartNo") on update no action on delete no action  

go

alter table "Purchase"
	add constraint "Party_Purchase_FK1" foreign key (
		"PartyId")
	 references "Party" (
		"Id") on update no action on delete no action  

go


/* This is the end of the Microsoft Visual Studio generated SQL DDL script.                   */
