#!/usr/bin/env python2
import traceback
import random
import socket
import argparse
import threading
import signal
import sys
import time
import requests
from contextlib import contextmanager

COMMANDSERVER_URL = ''

running = True
verbose = True
args = False

CLIENT2SERVER = 1
SERVER2CLIENT = 2

REPLAY_REQUEST = 2

REQUEST_COUNTER = 0
REPLAY_CONTENT = False

def mitm(buff, direction):
  global REQUEST_COUNTER
  global REPLAY_CONTENT

  hb = buff
  if direction == CLIENT2SERVER:
    REQUEST_COUNTER += 1

    if REQUEST_COUNTER == REPLAY_REQUEST:
      REPLAY_CONTENT = hb
    pass
  elif direction == SERVER2CLIENT:
    pass
  return hb

@contextmanager
def ignored(*exceptions):
  try:
    yield
  except exceptions:
    pass 

def killpn( a, b, n):
  if n != CLIENT2SERVER:
    killp( a, b)

def killp(a, b):
  with ignored(Exception):
    a.shutdown(socket.SHUT_RDWR)
    a.close()
    b.shutdown(socket.SHUT_RDWR)
    b.close()
  return

def worker(client, server, n):
  while running == True:
    b = ""
    with ignored(Exception):
      b = client.recv(1024)
    if len(b) == 0:
      killpn(client,server,n)
      return
    try:
      b = mitm(b,n)
    except:
      pass
    try:
      if b != None:
        server.send(b)

      if REPLAY_CONTENT != False and n == CLIENT2SERVER:
        replayMessage(REPLAY_CONTENT)
    except:
      killpn(client,server,n)
      return
  killp(client,server)
  return

def replayMessage(message):
  time.sleep(3)

  conn = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  try:
      conn.connect((args.s, args.q))
      conn.send(message)
            
  except socket.error:
      sys.stderr.write('Timeout/Connection error 63 \n')
      sys.exit(63)
      
  conn.close()

  time.sleep(3)

  request_cmd('{"type": "input","input":{"input": ["-p","%PORT%","-i","%IP%","-a","foo","-g"]}}')

  time.sleep(3)

  signalEnd()

def signalEnd():
  requests.post(COMMANDSERVER_URL, data={"REQUEST": '{"type": "done"}'})

def request_cmd(cmd):
  requests.post(COMMANDSERVER_URL, data={"REQUEST": cmd})

def signalhandler(sn, sf):
  running = False

def doProxyMain(port, remotehost, remoteport):
  signal.signal(signal.SIGTERM, signalhandler)
  try:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    s.bind(("0.0.0.0", port))
    s.listen(1)
    workers = []
    while running == True:
      k,a = s.accept()
      v = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
      v.connect((remotehost, remoteport))
      t1 = threading.Thread(target=worker, args=(k,v,CLIENT2SERVER))
      t2 = threading.Thread(target=worker, args=(v,k,SERVER2CLIENT))
      t2.start()
      t1.start()
      workers.append((t1,t2,k,v))
  except KeyboardInterrupt:
    signalhandler(None, None)
  for t1,t2,k,v in workers:
    killp(k,v)
    t1.join()
    t2.join()
  return

if __name__ == '__main__':
  global COMMANDSERVER_URL
  global args
  parser = argparse.ArgumentParser(description='Proxy')
  parser.add_argument('-p', type=int, default=4000, help="listen port")
  parser.add_argument('-s', type=str, default="127.0.0.1", help="server ip address")
  parser.add_argument('-q', type=int, default=3000, help="server port")
  parser.add_argument('-c', type=str, default="127.0.0.1", help="command server")
  parser.add_argument('-d', type=int, default=5000, help="command port")
  args = parser.parse_args()

  COMMANDSERVER_URL = "http://"+args.c+":"+str(args.d)

  print('started\n')
  sys.stdout.flush()
  doProxyMain(args.p, args.s, args.q)
