#!/bin/bash
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
echo "started"
sleep 1
# (>&2 echo "starting bash script, executing mitm.py ...")
# (cd "$THIS_DIR"; make)
"$THIS_DIR/bank" -s fake.auth -p 4411 1>&2 &
python3 "$THIS_DIR/mitm.py" "$@" 1>&2
